on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}

  pypi:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: deps
        run: pip3 install auditwheel

      - name: build wheels
        run: make bdist

      - name: fixup wheels
        run: |
          for whl in dist/*.whl; do
            auditwheel repair "${whl}" --plat manylinux2014_x86_64 -w dist/wheel/
          done

      - name: publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: dist/wheel/
